alter table public.orders
  add column if not exists order_number bigint generated by default as identity,
  add column if not exists customer_phone text,
  add column if not exists fulfillment_type text not null default 'delivery',
  add column if not exists street text,
  add column if not exists address_number text,
  add column if not exists neighborhood text,
  add column if not exists reference text;

create unique index if not exists idx_orders_order_number on public.orders(order_number);

alter table public.orders
  drop constraint if exists orders_fulfillment_type_check;

alter table public.orders
  add constraint orders_fulfillment_type_check
  check (fulfillment_type in ('delivery', 'pickup'));

comment on column public.orders.order_number is 'Número sequencial amigável exibido ao cliente';
comment on column public.orders.fulfillment_type is 'delivery = entrega; pickup = retirada';
